# Generated by Django 4.1.7 on 2023-03-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdmgnt', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
